# Connection properties
connectionString: "postgresql://user:password@localhost:5432/mermerd_test"
schema: 
  - "public"
  - "other_db"

# Define what tables should be used
#useAllTables: true
selectedTables:
  - article
  - label

# Additional flags
showAllConstraints: true
outputFileName: "my-db.mmd"
encloseWithMermaidBackticks: false
debug: false
omitConstraintLabels: false
omitAttributeKeys: false
showEnumValues: false
