# Connection properties
connectionString: "postgresql://user:password@localhost:5432/mermerd_test"
schema: "public"
debug: false

# Define what tables should be used
#useAllTables: true
selectedTables:
  - article
  - label

# Additional flags
showAllConstraints: true
outputFileName: "my-db.mmd"
encloseWithMermaidBackticks: false
