# Connection properties
connectionString: "postgresql://user:password@localhost:5432/mermerd_test"

# Define what tables should be used
#useAllSchemas: true
schema: 
  - "public"
  - "other_db"

# Define what tables should be used
#useAllTables: true
selectedTables:
  - public.article
  - public.label

# Additional flags
showAllConstraints: true
outputFileName: "my-db.mmd"
encloseWithMermaidBackticks: false
debug: false
omitConstraintLabels: false
omitAttributeKeys: false
outputMode: stdout
showDescriptions:
  - enumValues
  - columnComments
  - notNull
relationshipLabels:
  - "public_article public_article_comment : has_many"
showSchemaPrefix: true
schemaPrefixSeparator: "_"
