// Code generated by mockery v2.21.4. DO NOT EDIT.

package mocks

import (
	database "github.com/KarnerTh/mermerd/database"

	mock "github.com/stretchr/testify/mock"
)

// Diagram is an autogenerated mock type for the Diagram type
type Diagram struct {
	mock.Mock
}

// Create provides a mock function with given fields: result
func (_m *Diagram) Create(result *database.Result) error {
	ret := _m.Called(result)

	var r0 error
	if rf, ok := ret.Get(0).(func(*database.Result) error); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDiagram interface {
	mock.TestingT
	Cleanup(func())
}

// NewDiagram creates a new instance of Diagram. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiagram(t mockConstructorTestingTNewDiagram) *Diagram {
	mock := &Diagram{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
