// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	database "mermerd/database"

	mock "github.com/stretchr/testify/mock"
)

// Diagram is an autogenerated mock type for the Diagram type
type Diagram struct {
	mock.Mock
}

// Create provides a mock function with given fields: result
func (_m *Diagram) Create(result *database.Result) error {
	ret := _m.Called(result)

	var r0 error
	if rf, ok := ret.Get(0).(func(*database.Result) error); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
