// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoadingSpinner is an autogenerated mock type for the LoadingSpinner type
type LoadingSpinner struct {
	mock.Mock
}

// Start provides a mock function with given fields: text
func (_m *LoadingSpinner) Start(text string) {
	_m.Called(text)
}

// Stop provides a mock function with given fields:
func (_m *LoadingSpinner) Stop() {
	_m.Called()
}
