// Code generated by mockery v2.21.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoadingSpinner is an autogenerated mock type for the LoadingSpinner type
type LoadingSpinner struct {
	mock.Mock
}

// Start provides a mock function with given fields: text
func (_m *LoadingSpinner) Start(text string) {
	_m.Called(text)
}

// Stop provides a mock function with given fields:
func (_m *LoadingSpinner) Stop() {
	_m.Called()
}

type mockConstructorTestingTNewLoadingSpinner interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoadingSpinner creates a new instance of LoadingSpinner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoadingSpinner(t mockConstructorTestingTNewLoadingSpinner) *LoadingSpinner {
	mock := &LoadingSpinner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
